name: mdu1_launcher
description: A new Flutter project.
publish_to: 'none'
version: 1.0.3+4
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  device_apps: ^2.2.0
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  ota_update: ^4.0.1
  http: ^0.13.4
  device_info_plus: ^3.2.3
  package_info_plus: ^1.4.2
  scroll_to_index: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: false
  assets:
    - background.jpg