name: mdu1_launcher
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  device_apps: ^2.2.0
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: false
  assets:
    - background.jpg